database:
  csv_loaded: true
  name: gym_tracker
  path: db/gym_tracker.db
  tables_created: true
files:
  path: db/Gym Sheets.xlsx
  sheet: Gym Tracker
  table: gym_sessions
tables:
  gym_sessions:
    columns:
    - autoincrement: true
      name: id
      primary_key: true
      type: integer
    - excel_column: Day
      name: date
      type: text
    - excel_column: Minutes in Gym
      name: duration
      type: text
    - excel_column: Location
      name: gym_name
      type: text
    - excel_column: Exercise Category
      name: category
      type: text
  users:
    columns:
    - autoincrement: true
      name: id
      primary_key: true
      type: integer
    - name: username
      not_null: true
      type: text
    - name: email
      type: text
    - name: password
      not_null: true
      type: text
