tables:
  gym_sessions:
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: date
        excel_column: Day
        type: text
      - name: duration
        excel_column: "Minutes in Gym"
        type: integer
      - name: gym_name
        excel_column: "Location"
        type: text
      - name: category
        excel_column: "Exercise Category"
        type: text
  users:
    columns:
      - name: id
        type: integer
        primary_key: true
        autoincrement: true
      - name: username
        type: text
      - name: email
        type: text

files:
  path: "db/Gym Sheets.xlsx"
  sheet: "Gym Tracker"
  table: gym_sessions